name: failable

on:
  pull_request:
  push:

jobs:
  failable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # if './hoge' exists, this test passes
      - run: ls hoge
