name: on-status
on:
  status

jobs:
  on-status:
    runs-on: ubuntu-latest
    #if: >-
    #  github.event.state == 'error' ||
    #  github.event.state == 'failure'
    steps:
      - run: 'echo "event_name: ${{ github.event_name }}"'
      - run: cat $GITHUB_EVENT_PATH
