name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      some_choice:
        type: choice
        description: choiceのサンプル入力
        options:
          - foo
          - bar
          - baz
      some_text:
        required: true
        description: 必須テキスト入力サンプル

jobs:
  invoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: hello
        run: echo 'hello'
      - name: sleep
        run: sleep 5
      - name: bye
        run: echo 'bye'
